name: CI

on:
  push:
  pull_request:

jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest,windows-latest]
        python-version:
          - "3.10"
          - "3.11"
    name: Test
    runs-on: ${{ matrix.os }}

    env:
      SSW_MASTER_CPF: ${{ secrets.SSW_MASTER_CPF }}
      SSW_MASTER_DOMINIO: ${{ secrets.SSW_MASTER_DOMINIO }}
      SSW_MASTER_SENHA: ${{ secrets.SSW_MASTER_SENHA }}
      SSW_MASTER_UNIDADE: ${{ secrets.SSW_MASTER_UNIDADE }}
      SSW_MASTER_USUARIO: ${{ secrets.SSW_MASTER_USUARIO }}
      SSW_CPF: ${{ secrets.SSW_CPF }}
      SSW_DOMINIO: ${{ secrets.SSW_DOMINIO }}
      SSW_SENHA: ${{ secrets.SSW_SENHA }}
      SSW_UNIDADE: ${{ secrets.SSW_UNIDADE }}
      SSW_USUARIO: ${{ secrets.SSW_USUARIO }}
      # Add more secrets as needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python-version}}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Configure Git to use PAT
        run: |
          git config --global url."https://x-access-token:${{ secrets.MY_GITHUB_PAT }}@github.com/".insteadOf "https://github.com/"

      - name: Clone private repository
        env:
          GITHUB_PAT: ${{ secrets.MY_GITHUB_PAT }}
        run: |
          git clone https://github.com/cvltransportes/priority_classes.git
          cd priority_classes
          pip install .

      - name: Run tests
        run: pytest